#!/bin/bash

# /etc/init.d/sample.py
### BEGIN INIT INFO
# Provides:          main
# Required-Start:    $remote_fs $syslog $network $time
# Required-Stop:     $remote_fs $syslog $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: main
# Description:       main
### END INIT INFO


function start() {
	cd /home/pi/rpi-inkyphat
	git pull origin master
	/home/pi/rpi-inkyphat/main.py > /home/pi/main.log 2>&1 &
	echo $! > /home/pi/main.pid
}

function stop() {
	pid=$(cat /home/pi/main.pid)
	kill $pid
	sleep 10
	if [ -e /proc/$pid ]; then
		kill -9 $pid
		sleep 5
	fi
}

cmd=$1
shift
case $cmd in
	start) start $@ ;;
	stop) stop $@ ;;
	restart) stop $@ && start $@ ;;
esac
